# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-06 15:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0020_old_tree_cleanup'),
        ('js_components', '0002_auto_20190225_0516'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TwitterFeed',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='js_components_twitterfeed', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('username', models.CharField(max_length=255, verbose_name='twitter username')),
                ('count', models.IntegerField(default=3, verbose_name='number of tweets to show')),
                ('followers', models.IntegerField(editable=False, null=True)),
                ('layout', models.CharField(blank=True, default='', max_length=60, verbose_name='layout')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AddField(
            model_name='tweetcache',
            name='plugin_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='js_components.TwitterFeed'),
        ),
    ]
