# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 18:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_icon.fields
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0020_old_tree_cleanup'),
        ('js_components', '0003_auto_20190306_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='js_components_counter', serialize=False, to='cms.CMSPlugin')),
                ('body', models.CharField(max_length=255, verbose_name='caption body')),
                ('counter', models.CharField(max_length=255, verbose_name='counter')),
                ('icon', djangocms_icon.fields.Icon(blank=True, default='', max_length=255, null=True, verbose_name='Icon')),
                ('prefix', models.CharField(blank=True, max_length=255, null=True, verbose_name='prefix')),
                ('suffix', models.CharField(blank=True, max_length=255, null=True, verbose_name='suffix')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='CountersContainer',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='js_components_counterscontainer', serialize=False, to='cms.CMSPlugin')),
                ('layout', models.CharField(blank=True, default='', max_length=60, verbose_name='layout')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
