# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-25 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('js_components', '0004_counter_counterscontainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawHTML',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='js_components_rawhtml', serialize=False, to='cms.CMSPlugin')),
                ('body', models.TextField(verbose_name='HTML body')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
