# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('js_components', '0005_rawhtml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promounit',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
    ]
