# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-01 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('js_components', '0007_auto_20190429_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='content',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, default='', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='body',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
