# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-01 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('js_components', '0008_auto_20190501_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='layout',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='layout'),
        ),
    ]
