# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-10 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('js_components', '0010_auto_20190502_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='promounit',
            name='subtitle',
            field=models.CharField(max_length=255, null=True, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='promounit',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
    ]
