# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('js_components', '0011_auto_20190510_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promounit',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitle'),
        ),
    ]
