# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-05 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0011_auto_20190418_0137'),
        ('js_components', '0012_auto_20190514_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='filer.File')),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('filer.file',),
        ),
    ]
