# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-22 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('js_components', '0013_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='promounit',
            name='show_filesize',
            field=models.BooleanField(default=False, verbose_name='Show Filesize'),
        ),
    ]
