# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-30 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('js_components', '0014_promounit_show_filesize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promounit',
            name='show_filesize',
            field=models.BooleanField(default=True, verbose_name='Show Filesize'),
        ),
    ]
