# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-30 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('js_components', '0015_auto_20190730_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetcache',
            name='tweet_link',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
