# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-12 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('js_components', '0016_tweetcache_tweet_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promounit',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
    ]
