# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-23 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('js_components', '0017_auto_20190812_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawHTMLWithID',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='js_components_rawhtmlwithid', serialize=False, to='cms.CMSPlugin')),
                ('body', models.TextField(verbose_name='HTML body')),
                ('parameters', models.CharField(blank=True, help_text='comma separated', max_length=255, null=True, verbose_name='parameters')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
