# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-04 09:21
from __future__ import unicode_literals

from django.db import migrations
import js_components.models


class Migration(migrations.Migration):

    dependencies = [
        ('js_components', '0018_rawhtmlwithid'),
    ]

    operations = [
        migrations.AddField(
            model_name='promounit',
            name='attributes',
            field=js_components.models.AttributesField(blank=True, default=dict, verbose_name='Attributes'),
        ),
    ]
