# Generated by Django 2.2.10 on 2020-02-06 09:37

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('js_components', '0020_auto_20200206_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='promounit',
            name='rollover_content',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, default='', verbose_name='Rollover Content'),
        ),
    ]
