# Generated by Django 2.2.10 on 2020-02-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('js_components', '0021_promounit_rollover_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='promounit',
            name='modal_id',
            field=models.CharField(blank=True, default='', help_text='Do not include a preceding "#" symbol.', max_length=60, verbose_name='Modal Id'),
        ),
    ]
