# Generated by Django 2.2.10 on 2020-03-25 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('js_components', '0022_promounit_modal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatedContent',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='js_components_gatedcontent', serialize=False, to='cms.CMSPlugin')),
                ('layout', models.CharField(blank=True, default='', max_length=60, verbose_name='layout')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
