# Generated by Django 2.2.13 on 2020-06-15 10:32

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.folder


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0011_auto_20190418_0137'),
        ('cms', '0022_auto_20180620_1551'),
        ('js_components', '0024_animate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='js_components_folder', serialize=False, to='cms.CMSPlugin')),
                ('layout', models.CharField(blank=True, default='', max_length=60, verbose_name='layout')),
                ('title', models.CharField(blank=True, default='', max_length=60, verbose_name='title')),
                ('summary', djangocms_text_ckeditor.fields.HTMLField(blank=True, default='', verbose_name='summary')),
                ('order_by', models.CharField(blank=True, max_length=60, null=True, verbose_name='order by')),
                ('open_in_new_window', models.BooleanField(default=False, verbose_name='Open in new window')),
                ('folder', filer.fields.folder.FilerFolderField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='filer.Folder', verbose_name='select folder')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
