# Generated by Django 2.2.10 on 2020-09-11 09:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('js_components', '0026_includeexcludecontainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='custom_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
