# Generated by Django 2.2.16 on 2020-10-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('js_components', '0027_custom_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='animate',
            name='on_rollover',
            field=models.BooleanField(default=False, verbose_name='On Rollover'),
        ),
        migrations.AlterField(
            model_name='includeexcludecontainer',
            name='exclude',
            field=models.TextField(blank=True, default='', verbose_name='Hide on these pages'),
        ),
        migrations.AlterField(
            model_name='includeexcludecontainer',
            name='include',
            field=models.TextField(blank=True, default='*', help_text='Always start the URL without the domain or the first slash (/) (e.g. test/me). Use an asterisk  to show/hide on multiple pages (e.g. blog/* or *://test.com/*)', verbose_name='Show on these pages'),
        ),
    ]
