# Generated by Django 2.2.19 on 2021-03-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('js_components', '0029_float'),
    ]

    operations = [
        migrations.AddField(
            model_name='promounit',
            name='background_video',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Background Video'),
        ),
    ]
