# Generated by Django 2.2.19 on 2021-03-19 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('js_components', '0030_promounit_background_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lightbox',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='js_components_lightbox', serialize=False, to='cms.CMSPlugin')),
                ('layout', models.CharField(blank=True, default='', max_length=60, verbose_name='layout')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='title')),
                ('show_title', models.BooleanField(default=False, verbose_name='Show Title')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AddField(
            model_name='includeexcludecontainer',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='title'),
        ),
    ]
