# Generated by Django 2.2.24 on 2021-06-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('js_components', '0033_auto_20210616_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatedcontent',
            name='cookie_name',
            field=models.SlugField(blank=True, default='', max_length=255, verbose_name='cookie name'),
        ),
    ]
