# Generated by Django 2.2.24 on 2021-08-16 10:52

from django.db import migrations, models
import js_color_picker.fields


class Migration(migrations.Migration):

    dependencies = [
        ('js_components', '0034_auto_20210621_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='promounit',
            name='full_height',
            field=models.BooleanField(default=True, verbose_name='Full Height'),
        ),
    ]
