# Generated by Django 2.2.24 on 2021-11-19 11:45

from django.db import migrations, models
import js_color_picker.fields


class Migration(migrations.Migration):

    dependencies = [
        ('js_components', '0036_auto_20210915_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='promounit',
            name='alignment',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Alignment'),
        ),
    ]
