# Generated by Django 2.2.24 on 2022-10-10 10:33

from django.db import migrations, models
import js_color_picker.fields


class Migration(migrations.Migration):

    dependencies = [
        ('js_components', '0037_auto_20211119_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatedcontent',
            name='link_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Link URL'),
        ),
        migrations.AlterField(
            model_name='promounit',
            name='color',
            field=js_color_picker.fields.RGBColorField(blank=True, colors={'#0073CF': 'Blue 2', '#00B0CA': 'Blue 1', '#00ae65': 'green', '#0D2240': 'dark-blue', '#4d4d4d': 'grey', '#5E6A71': 'dark-grey', '#67B2E8': 'pale-blue', '#808080': 'middle-grey', '#C3009E': 'Purple', '#CAD7E6': 'Light 2', '#D1EAEC': 'Light 1', '#E00034': 'Dark red', '#E1F0FA': 'palest-blue', '#E8CFDC': 'Light purple', '#F0AB00': 'Dark yellow', '#F7D1C2': 'Light red', '#FEEDCA': 'Light yellow', '#ccc': 'light-grey', '#eee': 'lightest-grey', '#fff': 'white'}, mode='choice', null=True, verbose_name='Color'),
        ),
    ]
