# Generated by Django 2.2.28 on 2023-02-14 12:43

from django.db import migrations, models
import js_color_picker.fields


class Migration(migrations.Migration):

    dependencies = [
        ('js_components', '0038_auto_20221010_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightbox',
            name='max_visible_images',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='max visible images'),
        ),
    ]
